[level_1]
  [level_1.nonlured]
    [level_1.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_1.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_1.lured]
    [level_1.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_1.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_2]
  [level_2.nonlured]
    [level_2.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_2.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_2.lured]
    [level_2.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_2.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_3]
  [level_3.nonlured]
    [level_3.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_3.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_3.lured]
    [level_3.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_3.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_4]
  [level_4.nonlured]
    [level_4.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_4.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_4.lured]
    [level_4.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_4.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_5]
  [level_5.nonlured]
    [level_5.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_5.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_5.lured]
    [level_5.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_5.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_6]
  [level_6.nonlured]
    [level_6.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_6.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_6.lured]
    [level_6.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_6.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_7]
  [level_7.nonlured]
    [level_7.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_7.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_7.lured]
    [level_7.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_7.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_8]
  [level_8.nonlured]
    [level_8.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_8.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_8.lured]
    [level_8.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_8.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_9]
  [level_9.nonlured]
    [level_9.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_9.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_9.lured]
    [level_9.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_9.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_10]
  [level_10.nonlured]
    [level_10.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_10.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_10.lured]
    [level_10.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_10.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_11]
  [level_11.nonlured]
    [level_11.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_11.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_11.lured]
    [level_11.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_11.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_12]
  [level_12.nonlured]
    [level_12.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_12.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_12.lured]
    [level_12.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_12.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_9_v2]
  [level_9_v2.nonlured]
    [level_9_v2.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_9_v2.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_9_v2.lured]
    [level_9_v2.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_9_v2.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_10_v2]
  [level_10_v2.nonlured]
    [level_10_v2.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_10_v2.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_10_v2.lured]
    [level_10_v2.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_10_v2.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_11_v2]
  [level_11_v2.nonlured]
    [level_11_v2.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_11_v2.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_11_v2.lured]
    [level_11_v2.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_11_v2.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
[level_12_v2]
  [level_12_v2.nonlured]
    [level_12_v2.nonlured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_12_v2.nonlured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
  [level_12_v2.lured]
    [level_12_v2.lured.nonorg]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
    [level_12_v2.lured.org]
      throw  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      squirt = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      drop   = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
      sound  = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]
